/*    */ package com.avaje.ebean.config.dbplatform;
/*    */ 
/*    */ import com.avaje.ebean.BackgroundExecutor;
/*    */ import javax.sql.DataSource;
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ public class DB2Platform
/*    */   extends DatabasePlatform
/*    */ {
/*    */   public DB2Platform() {
/* 35 */     this.name = "db2";
/*    */ 
/*    */ 
/*    */     
/* 39 */     this.dbIdentity.setSupportsGetGeneratedKeys(true);
/* 40 */     this.dbIdentity.setIdType(IdType.IDENTITY);
/* 41 */     this.dbIdentity.setSupportsSequence(true);
/*    */     
/* 43 */     this.openQuote = "\"";
/* 44 */     this.closeQuote = "\"";
/*    */ 
/*    */     
/* 47 */     this.booleanDbType = 4;
/* 48 */     this.dbTypeMap.put(16, new DbType("smallint default 0"));
/* 49 */     this.dbTypeMap.put(4, new DbType("integer"));
/* 50 */     this.dbTypeMap.put(-5, new DbType("bigint"));
/* 51 */     this.dbTypeMap.put(7, new DbType("float"));
/* 52 */     this.dbTypeMap.put(8, new DbType("float"));
/* 53 */     this.dbTypeMap.put(5, new DbType("smallint"));
/* 54 */     this.dbTypeMap.put(-6, new DbType("smallint"));
/* 55 */     this.dbTypeMap.put(3, new DbType("decimal", 15));
/*    */     
/* 57 */     this.dbDdlSyntax.setIdentity("generated by default as identity");
/*    */   }
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */   
/* 73 */   public IdGenerator createSequenceIdGenerator(BackgroundExecutor be, DataSource ds, String seqName, int batchSize) { return new DB2SequenceIdGenerator(be, ds, seqName, batchSize); }
/*    */ }


/* Location:              C:\Users\calmilamsy\Downloads\craftbukkit-1092-0f15ea67210f5e56ac6a23b7a714564654888e9f.jar!\com\avaje\ebean\config\dbplatform\DB2Platform.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       1.0.4
 */