/*    */ package com.avaje.ebean.config.dbplatform;
/*    */ 
/*    */ import com.avaje.ebean.BackgroundExecutor;
/*    */ import com.avaje.ebean.config.GlobalProperties;
/*    */ import javax.sql.DataSource;
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ public class HsqldbPlatform
/*    */   extends DatabasePlatform
/*    */ {
/*    */   public HsqldbPlatform() {
/* 41 */     boolean useIdentity = GlobalProperties.getBoolean("ebean.hsqldb.useIdentity", true);
/*    */     
/* 43 */     IdType idType = useIdentity ? IdType.IDENTITY : IdType.SEQUENCE;
/* 44 */     this.dbIdentity.setIdType(idType);
/*    */     
/* 46 */     this.dbIdentity.setSupportsGetGeneratedKeys(true);
/* 47 */     this.dbIdentity.setSupportsSequence(true);
/* 48 */     this.dbIdentity.setSupportsIdentity(true);
/*    */     
/* 50 */     this.openQuote = "\"";
/* 51 */     this.closeQuote = "\"";
/*    */ 
/*    */ 
/*    */     
/* 55 */     this.dbTypeMap.put(4, new DbType("integer", false));
/*    */     
/* 57 */     this.dbDdlSyntax.setDropIfExists("if exists");
/* 58 */     this.dbDdlSyntax.setDisableReferentialIntegrity("SET DATABASE REFERENTIAL INTEGRITY FALSE");
/* 59 */     this.dbDdlSyntax.setEnableReferentialIntegrity("SET DATABASE REFERENTIAL INTEGRITY TRUE");
/* 60 */     this.dbDdlSyntax.setForeignKeySuffix("on delete restrict on update restrict");
/* 61 */     this.dbDdlSyntax.setIdentity("GENERATED BY DEFAULT AS IDENTITY (START WITH 1) ");
/*    */   }
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */   
/* 72 */   public IdGenerator createSequenceIdGenerator(BackgroundExecutor be, DataSource ds, String seqName, int batchSize) { return new H2SequenceIdGenerator(be, ds, seqName, batchSize); }
/*    */ }


/* Location:              C:\Users\calmilamsy\Downloads\craftbukkit-1092-0f15ea67210f5e56ac6a23b7a714564654888e9f.jar!\com\avaje\ebean\config\dbplatform\HsqldbPlatform.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       1.0.4
 */